application:
  name: beyan-real-estates12
  project: beyan_real_estates12
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: my-db
routers:
- name: main
  routes:
  - application_name: beyan-real-estates12
    paths:
    - /
