# Generated by Django 3.0.5 on 2020-05-06 06:15

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='unique_id')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=blog.models.post_upload_to, verbose_name='cover')),
                ('type', models.CharField(choices=[('House', 'House'), ('Car', 'Car')], default='House', max_length=10, verbose_name='type')),
                ('is_open', models.BooleanField(default=True, verbose_name='is open')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.posts_upload_to, verbose_name='image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
